version: '3'

services:
  web:
    image: smarthotels/twsentiment-client
    build:
      context: ./web
      dockerfile: Dockerfile  
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001

